queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=Integration Test"
      - "label=ready-to-merge"
    merge_conditions:
      - "status-success=Integration Test"

pull_request_rules:
  - name: automatic merge on CI success and approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=Integration Test"
      - "label=ready-to-merge"
    actions:
      queue:
        name: default
        method: merge

  - name: add to merge queue when CI passes after approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=Integration Test"
      - "-label=ready-to-merge"
      - "-draft"
    actions:
      label:
        add:
          - "ready-to-merge"

  - name: remove from queue on CI failure
    conditions:
      - "label=ready-to-merge"
      - "-status-success=Integration Test"
    actions:
      label:
        remove:
          - "ready-to-merge"

  - name: automatic merge for dependabot after approval
    conditions:
      - "author=dependabot[bot]"
      - "#approved-reviews-by>=1"
      - "status-success=Integration Test"
    actions:
      queue:
        name: default
        method: merge